### ISSUE TITLE
Syphon Library not loaded

### ISSUE THREAD

**Issue by vibber** [vade/chromium#10]
So I'm almost there. But when I try to launch Chromium with

`out/Default/Chromium.app/Contents/MacOS/Chromium `

I get

```
dlopen /Users/vibber/Desktop/Syphonium_sync_branch/src/out/Default/Chromium.app/Contents/MacOS/../Versions/60.0.3108.0/Chromium Framework.framework/Chromium Framework: dlopen(/Users/vibber/Desktop/Syphonium_sync_branch/src/out/Default/Chromium.app/Contents/MacOS/../Versions/60.0.3108.0/Chromium Framework.framework/Chromium Framework, 261): Library not loaded: @loader_path/../Frameworks/Syphon.framework/Versions/A/Syphon
  Referenced from: /Users/vibber/Desktop/Syphonium_sync_branch/src/out/Default/./libcapture_lib.dylib
  Reason: image not found
Abort trap: 6
```

So apparently syphon fails to load. Can I perhaps just copy the framework into the bundle? I tried different places but no luck. I don't really care how if I can just get it to work.

**Comment by vade** [comment]
Yup that’s what I’d do. I built a Xcode project with that and install name tool library loader path change iirc. Nice work!

   
   

 http://vade.info

**Comment by vibber** [comment]
Sorry, I don't know how to build an Xcode project from that. Could you elaborate?

**Comment by vibber** [comment]
OK, so build Xcode project with gn? Will try. Perhaps you could elaborate 'install name tool library loader path change iirc.' I don't understand that sentence at all.

**Comment by vade** [comment]
Man install_name_tool in terminal. Helps adjust linked library loading paths in binaries. 

   
   

 http://vade.info

**Comment by vibber** [comment]
Ok so I manually copied the Syphon.framework into out/Default (my build dir), and then I ran:

`install_name_tool -change @loader_path/../Frameworks/Syphon.framework/Versions/A/Syphon @loader_path/Syphon.framework/Versions/A/Syphon out/Default/libcapture_lib.dylib`

That worked and Chromium starts.
(Now I get a crash after ~1 min but that's another problem)
