### ISSUE TITLE
Crash after ~1 min

### ISSUE THREAD

**Issue by vibber** [vade/chromium#11]
I hope you don't mind me documenting my experiences here. But I had an issue with my build of Chromium crashing after one minute. The crash log said 

`[1189:775:0207/104734.031667:FATAL:plugin_finder.cc(302)] Check failed: identifier_plugin_.find(identifier) == identifier_plugin_.end(). `

This was on a debug build. I solved it by doing a Release build. I prepared a release build by entering

`gn args out/Default`

I then entered in the editor

`is_debug = false`

For the record I *think* you could also enter these arguments

```
is_debug = true
dcheck_always_on = false
```

to solve the problem while still having a debug build

**Comment by vade** [comment]
That crash seems more like a chrome issue - I had no crashing issues release or debug at earlier build numbers. 

   
   

 http://vade.info
